import { FlaskConical } from "lucide-react"

export function SimulationBanner() {
  return (
    <div
      role="status"
      className="border-b border-warning/20 bg-warning-soft text-warning"
    >
      <div className="mx-auto flex max-w-6xl items-center gap-2 px-4 py-1.5 text-xs font-medium sm:px-6">
        <FlaskConical className="size-3.5" aria-hidden />
        <span className="tracking-wide uppercase">Simulation</span>
        <span className="text-warning/80">
          Data below is generated by fixtures. No real payouts are shown.
        </span>
      </div>
    </div>
  )
}
